export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_AUTH_ERROR_REMOVE = 'USER_AUTH_ERROR_REMOVE';
export const LOGOUT = 'LOGOUT';
export const FETCH_AIRPORTS = 'FETCH_AIRPORTS';
export const FETCH_ALL_AIRPORTS = 'FETCH_ALL_AIRPORTS';
export const FETCH_TOP_FIVE_AIRPORTS = 'FETCH_TOP_FIVE_AIRPORTS';
export const EDIT_AIRPORT = 'EDIT_AIRPORT';
export const ADD_AIRPORT = 'ADD_AIRPORT';
export const SUCCESS_ERROR_REMOVE_AIRPORT = 'SUCCESS_ERROR_REMOVE_AIRPORT';
export const AIRPORT_ERROR = 'AIRPORT_ERROR';
export const FETCH_AIRPORTS_SUMMARY = 'FETCH_AIRPORTS_SUMMARY';
export const FETCH_ALL_AIRPORTS_SUMMARY = 'FETCH_ALL_AIRPORTS_SUMMARY';
export const FETCH_AIRCRAFTS = 'FETCH_AIRCRAFTS';
export const EDIT_AIRCRAFT = 'EDIT_AIRCRAFT';
export const ADD_AIRCRAFT = 'ADD_AIRCRAFT';
export const FETCH_ALL_AIRCRAFTS = 'FETCH_ALL_AIRCRAFTS';
export const SUCCESS_ERROR_REMOVE_AIRCRAFT = 'SUCCESS_ERROR_REMOVE_AIRCRAFT';
export const AIRCRAFT_ERROR = 'AIRCRAFT_ERROR';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_ALL_TRANSACTIONS = 'FETCH_ALL_TRANSACTIONS';
export const SUCCESS_ERROR_REMOVE_TRANSACTION =
	'SUCCESS_ERROR_REMOVE_TRANSACTION';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const FETCH_FUEL_CONSUMPTION = 'FETCH_FUEL_CONSUMPTION';
export const REVERSE_TRANSACTION = 'REVERSE_TRANSACTION';
export const FETCH_ALL_FUEL_CONSUMPTION = 'FETCH_ALL_FUEL_CONSUMPTION';

// for cleanup

export const CLEAN_AIRPORTS = 'CLEAN_AIRPORTS';
export const CLEAN_AIRPORTS_SUMMARY = 'CLEAN_AIRPORTS_SUMMARY';
export const CLEAN_AIRCRAFTS = 'CLEAN_AIRCRAFTS';
export const CLEAN_TRANSACTIONS = 'CLEAN_TRANSACTIONS';
export const CLEAN_CHARTS_DATA = 'CLEAN_CHARTS_DATA';
