import airport from './airport.png';
import airport1 from './airport1.png';
import airport2 from './airport2.png';
import airport3 from './airport3.png';
import airport_logo from './airport_logo.png';
import right_arrow from './right_arrow.png';
import left_arrow from './left_arrow.png';
import left_arrow_disabled from './left_arrow_disabled.png';
import right_arrow_disabled from './right_arrow_disabled.png';
import sort from './sort.png';
import edit from './edit.png';
import reverse from './reverse.png';
import search from './search.png';

export const airportImage = airport;
export const airportOne = airport1;
export const airportTwo = airport2;
export const airportThree = airport3;
export const airportLogo = airport_logo;
export const rightArrow = right_arrow;
export const leftArrow = left_arrow;
export const rightArrowDisabled = right_arrow_disabled;
export const leftArrowDisabled = left_arrow_disabled;
export const sortIcon = sort;
export const editIcon = edit;
export const reverseTransactionIcon = reverse;
export const searchIcon = search;
